apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: goticket-dev-434422
  artifacts:
    - image: us.gcr.io/goticket-dev-434422/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/goticket-dev-434422/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'pages/**/*.js'
            dest: .
          - src: '**/*.js'
            dest: .
    - image: us.gcr.io/goticket-dev-434422/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/goticket-dev-434422/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/goticket-dev-434422/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/goticket-dev-434422/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
