# Name of the workflow
name: tests-auth

# Trigger
on:
  pull_request:
    # specify the files that will trigger the workflow
    paths:
      - 'auth/**'

# Actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get all codes from the project
      - uses: actions/checkout@v2
      # Run all tests in auth service
      - run: cd auth && npm install && npm run test:ci
